---
- name: Configure the Oracle APT key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: Configure the Oracle APT 2016 key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Configure the VirtualBox APT repositories
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present


- name: Install VirtualBox
  apt:
    pkg: virtualbox-{{ virtualbox_version }}
    state: present
    update_cache: yes
 
- name: Download Virtualbox extpack
  get_url:
    url: https://download.virtualbox.org/virtualbox/5.1.38/Oracle_VM_VirtualBox_Extension_Pack-5.1.38.vbox-extpack
    dest: /tmp
    mode: 0644

- name: Install Virtualbox extpack
  command: echo y | vboxmanage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.1.38.vbox-extpack creates=/usr/lib/virtualbox/ExtensionPacks/Oracle_VM_VirtualBox_Extension_Pack
